services:
  youve-got-mail:
    build: 
      context: .
      target: development
    image: youve-got-mail
    container_name: youve-got-mail
    ports:
      - "3000:3000"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: password

  youve-got-mail-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes: 
      - mongodb-data:/data
      
  youve-got-mail-rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - "5672:5672"
      - "15672:15672"
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mongodb-data:
  rabbitmq-data: